### ISSUE TITLE
More specific OS requirements

### ISSUE THREAD

**Issue by mert-kurttutan** [Abdenasser/neohtop#1]
Congrats on the projects

I assume htop will work for unix based OS. But, in the description, it say 
`A modern, cross-platform system monitor`

It would be better to more specific, say something like, it works on unix-based os, (or macos/linux)

**Comment by Abdenasser** [comment]
thank you @mert-kurttutan for the heads up, it would be great if you can push that in a PR.. otherwise you are totally right.

**Comment by Abdenasser** [comment]
actually, we can take some time to build for windows and linux (as neohtop is not built on top of htop itself)

**Comment by Abdenasser** [comment]
Linux was added in [475f97d](https://github.com/Abdenasser/neohtop/commit/475f97db79badd5e4d9966882a8f66b7eb2fae8e)
