### ISSUE TITLE
Memory usage mismatch

### ISSUE THREAD

**Issue by AleksandrZhukov** [Abdenasser/neohtop#10]
Activity monitor memory usage vs neohthop
<img width="410" alt="Screenshot 2024-11-05 at 17 29 25" src="https://github.com/user-attachments/assets/b68ca00c-ec8a-4f8a-a399-846a6dc542fa">

**Comment by Abdenasser** [comment]
@AleksandrZhukov the cached result is not really calculated, @laciferin2024 I think we should just remove it

**Comment by laciferin2024** [comment]
Your cache is too low. in my case its calculated

**Comment by laciferin2024** [comment]
> @AleksandrZhukov the cached result is not really calculated, @laciferin2024 I think we should just remove it

Well its calculated @AleksandrZhukov , its just that ur cache is too low. If u had a 8gb m1, u could have seen higher numbers. Cache calculation alg just like rest of metrics needs some of error correction. If u can bump up the cached files to 4GB you should start seeing 1GB+ cache

**Comment by laciferin2024** [comment]
@Abdenasser @AleksandrZhukov i think there seems to be a similar issue for Stats: https://github.com/exelban/stats/ which is written swift. 

I tried it, and i see 1GB+ memory difference between it and activity monitor.

**Comment by Abdenasser** [comment]
we can show virtual memory as well
