### ISSUE TITLE
Auto update

### ISSUE THREAD

**Issue by Erik262** [Abdenasser/neohtop#100]
**Is your feature request related to a problem? Please describe.**
I need to visit GitHub to check for new updates.

**Describe the solution you'd like**
Auto update within the app

**Describe alternatives you've considered**
There is no..

**Additional context**
Nice App :)

**Comment by Abdenasser** [comment]
what do you mean by I need to visit GitHub to check for new updates? the app already tells you if there's a new update.. or you mean downloading the update ?

**Comment by Erik262** [comment]
Neohtop didn't inform me about a new update. I need to visit this repository and check the version number to see if there is a newer one. Auto download and installation of the latest version would be nice.

**Comment by Abdenasser** [comment]
we just added the update notification in the previous version
