### ISSUE TITLE
Program doesn't start properly

### ISSUE THREAD

**Issue by olesya-wo** [Abdenasser/neohtop#101]
After launching, only an empty white window appears and these errors:
```
> ./NeoHtop_1.1.0_x86_64.AppImage 
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 1280x900: Permission denied
```
(the same with `sudo`)

System:
```
    Kernel: 6.8.0-47-generic x86_64 bits: 64 compiler: N/A
    Desktop: Cinnamon 5.4.12 tk: GTK 3.24.33 wm: Mutter 42.9 vt: 7
    dm: LightDM 1.30.0 Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
```

**Comment by olesya-wo** [comment]
No, it's my architecture, otherwise I'm getting `marked as an executable but could not be run by the operating system` error

**Comment by olesya-wo** [comment]
Looks lite it's a Tauri-related problem - https://github.com/tauri-apps/tauri/issues/8462

**Comment by Pinguin2001** [comment]
> Looks lite it's a Tauri-related problem - [tauri-apps/tauri#8462](https://github.com/tauri-apps/tauri/issues/8462)

It seems to be an issue related to WebKitGtk + gpu drivers and not Tauri, if im reading it correctly.

**Comment by Pinguin2001** [comment]
@olesya-wo Are you using an nvidia gpu?

**Comment by olesya-wo** [comment]
@Pinguin2001 Yes, but unfortunately none of these methods helped me
