### ISSUE TITLE
Some progress show 0% instead of others

### ISSUE THREAD

**Issue by nasyxx** [Abdenasser/neohtop#104]
**Describe the bug**

Some progress show 0% instead of the actual value.

**To Reproduce**
1. Build gcc14 with macports

**Expected behavior**
Show in in screenshots

**Screenshots**

<img width="1110" alt="Screenshot 2024-11-11 at 3 22 09 PM" src="https://github.com/user-attachments/assets/2ac6dccf-ff48-4025-bd89-3877db8b2ad4">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 15.1 (24B2083)

**Additional context**

**Comment by Abdenasser** [comment]
closing as issue is not reproducible

**Comment by nasyxx** [comment]
I don't think this is impossible to reproduce. In fact, I discovered some processes that can be seen in Activity Monitor but not in neotop. The most obvious example is WindowServer.  

<img width="1296" alt="Screenshot 2024-11-12 at 7 28 58 AM" src="https://github.com/user-attachments/assets/7faeea97-2abb-4528-9422-4a3ad908cc94">

**Comment by Abdenasser** [comment]
![Screenshot 2024-11-12 at 15 17 10](https://github.com/user-attachments/assets/e0155926-59a3-4a87-9fb7-1b49f7edfa68)
well neohtop and htop are reporting same results

**Comment by Abdenasser** [comment]
I often don't need to use sudo with both htop and neohtop

**Comment by nasyxx** [comment]
Is it possible to use sudo internally rather than launching with sudo? Many services (both linux and macos) are mounted with sudo privileges and start automatically at boot, rather than being mounted under the user account.

---

I tried sudo neohtop here:

<img width="984" alt="Screenshot 2024-11-12 at 9 06 16 AM" src="https://github.com/user-attachments/assets/bcd29874-ed58-44e4-af9c-6562e2cba43b">

**Comment by Abdenasser** [comment]
I don't think that's something Tauri supports yet, but would invite you to add a section on the readme that mentions how to monitor processes that are sudo launched.

**Comment by Abdenasser** [comment]
@nasyxx I like that thank you, you can add it in the Features section just below the list of the features!
