### ISSUE TITLE
Query: host tauri backend in a remote machine and plug into the desktop frontend

### ISSUE THREAD

**Issue by laciferin2024** [Abdenasser/neohtop#12]
@Abdenasser 

Would u mind laying out the steps to host tauri dev backend in a remote ssh machine and plug it to the frontend?

Ref #7

**Comment by Abdenasser** [comment]
@laciferin2024 what for ?

**Comment by Abdenasser** [comment]
oh, I think you mean for us to build the linux image.. we can instead setup github actions to do that for us, but i also want to test it and play with it myself.. I'll maybe setup a virtual machine on my computer with ubuntu or some other distribution

**Comment by laciferin2024** [comment]
> @laciferin2024 what for ?

I want to bring in cross platform support. I think its possible for us to make a chrome app, remote visual appealing htop. I have a valid use case where i have a couple of my vms and I want to monitor the processes from time to time via neohtop. But they all necessitate either frontend decoupling or Remote Desktop protocol

**Comment by Abdenasser** [comment]
it's cross platform, but it's a desktop app.. unless I'm understanding this wrong, you want frontend and backend to be separate/ or expose an API from the desktop/ or use tauri just as a frontend to talk to some rust agent on a different machine!

**Comment by laciferin2024** [comment]
Yeah u guessed it right. Under the hood, tauri should be using websockets to run the rust code. So it should be possible to decouple the tauri backend.

**Comment by Abdenasser** [comment]
@laciferin2024 this might be a good feature to implement, I can image people using  NeoHtop and connecting it through http or tcp with a NeoHtop agent running on some server.. lets start using github discussions instead of issues

**Comment by laciferin2024** [comment]
Ok, sounds good
