### ISSUE TITLE
Advanced search operator

### ISSUE THREAD

**Issue by egoist** [Abdenasser/neohtop#13]
For example an OR operator for matching multiple conditions, I often want to compare the usage of multiple programs.

![CleanShot 2024-11-06 at 15 01 21@2x](https://github.com/user-attachments/assets/35d77fcc-68af-4495-bb5a-9adc9a4e9779)

**Comment by Abdenasser** [comment]
interesting, thank you.. will consider supporting that somehow (will see if we can come up with some better experience though)

**Comment by Abdenasser** [comment]
@egoist but still you can achieve something similar by pinning two or more processes and comparing

**Comment by egoist** [comment]
@Abdenasser that's right, i didn't know that. but a search keyword would be easier and better for one-off usage

**Comment by Abdenasser** [comment]
will think about it, but not a priority for now.. thank you @egoist
