### ISSUE TITLE
Available storage mismatch

### ISSUE THREAD

**Issue by dyanakiev** [Abdenasser/neohtop#14]
I'm running macOS 15.1 on my MacBook Air M1. I have 250 GB of internal storage, but the app reports double that amount.

![CleanShot 2024-11-06 at 09 31 37@2x](https://github.com/user-attachments/assets/03e1537c-3a79-41f9-aaa0-dcf276ab0bd8)

**Comment by Abdenasser** [comment]
the issue is that sys.disks() returns all mounted disks, including network drives, time machine backups, and other mounted volumes. working on a fix.

**Comment by Abdenasser** [comment]
thank you @dyanakiev for reporting
