### ISSUE TITLE
Homebrew method

### ISSUE THREAD

**Issue by MoKhajavi75** [Abdenasser/neohtop#15]
Hey

Thanks for your awesome tool, just wanted to know if you plan to add homebrew method to install this.

**Comment by Abdenasser** [comment]
will consider that, thank you!

**Comment by davidaparicio** [comment]
I know it's a Rust application with Tauri. But, maybe, it's possible to perform something like [GoReleaser (Aurélie Vache tuto)](https://dev.to/aurelievache/learning-go-by-examples-part-9-use-homebrew-goreleaser-for-distributing-a-golang-app-44ae)

I agree with @MoKhajavi75, my first reaction as a mac user was to perform a `brew install neohtop` on my iTerm 👍 

I would like to take this opportunity to say that I have installed the .dmg file and I congratulate you on your magnificent project, which is terribly efficient!! 💯
