### ISSUE TITLE
how to by pass the signing part.

### ISSUE THREAD

**Issue by hliao** [Abdenasser/neohtop#17]

**Comment by hliao** [comment]
Using @sveltejs/adapter-static
  Wrote site to "build"
  ✔ done
   Compiling macos-task-manager v1.0.5 (/Users/hongtao/code/neohtop/src-tauri)
    Finished `release` profile [optimized] target(s) in 39.12s
        Warn Signing, by default, is only supported on Windows hosts, but you can specify a custom signing command in `bundler > windows > sign_command`, for now, skipping signing the installer...
    Bundling NeoHtop.app (/Users/hongtao/code/neohtop/src-tauri/target/release/bundle/macos/NeoHtop.app)
     Signing with identity "Developer ID Application: Abdenasser Elidrissi (785JV74B9Y)"
        Info Signing app bundle...
     Signing /Users/hongtao/code/neohtop/src-tauri/target/release/bundle/macos/NeoHtop.app/Contents/MacOS/NeoHtop
       Error failed to bundle project: failed to sign app

**Comment by Abdenasser** [comment]
don't use `-bundles dmg`, just use the `npm run tauri build` or `npm run tauri dev`

**Comment by Abdenasser** [comment]
the final build would be in your `src-tauri/target`
