### ISSUE TITLE
Window is too tall for 13" MacBook Air

### ISSUE THREAD

**Issue by alinnert** [Abdenasser/neohtop#23]
As the title says: the app doesn't fit on the screen and I cannot resize it vertically.

**Comment by Abdenasser** [comment]
will push a fix for that in the next release, thanks for reporting @alinnert

**Comment by alinnert** [comment]
Sure, here's a screenshot. I can make the window bigger but not smaller.

![CleanShot 2024-11-07 - 001184](https://github.com/user-attachments/assets/92fc1c13-6266-47df-9365-20bb8785d349)

**Comment by laciferin2024** [comment]
I think its a resolution issue. Which resolution are u on?

<img width="1710" alt="image" src="https://github.com/user-attachments/assets/c776a285-9186-4275-a25c-fda6c1717dff">

**Comment by laciferin2024** [comment]
<img width="1186" alt="image" src="https://github.com/user-attachments/assets/f30c5bed-2d4b-49d9-91aa-f16d746a9bb3">

**Comment by alinnert** [comment]
I can't make screenshots right now but I've looked it up. It's the default resolution. Also, I'm using a M1 MacBook Air. It doesn't have a notch yet, if that makes some difference.

I've also noticed that there are fewer entries in the list inside the viewport in the screenshot by @laciferin2024.

**Comment by laciferin2024** [comment]
THe second screenshot is resized to the smallest size i can get it to be.

I use the highest res not the default res

**Comment by Abdenasser** [comment]
@alinnert we have these constraint
        "minWidth": 1280,
        "minHeight": 900
you can maybe open a PR based on what you should be good enough for small screens

**Comment by laciferin2024** [comment]
> Sure, here's a screenshot. I can make the window bigger but not smaller.
> 
> ![CleanShot 2024-11-07 - 001184](https://private-user-images.githubusercontent.com/2638971/383765223-92fc1c13-6266-47df-9365-20bb8785d349.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDQ2OTgsIm5iZiI6MTczMTAwNDM5OCwicGF0aCI6Ii8yNjM4OTcxLzM4Mzc2NTIyMy05MmZjMWMxMy02MjY2LTQ3ZGYtOTM2NS0yMGJiODc4NWQzNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDdUMTgzMzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZiNWMxYWFiM2Y5OTc5NjlmYTIyMWQzY2RjNjVkZWYxMDNkMDdiN2QxMDVkMzQzZjgwZTk1ZjE4OWYxZDAwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.kx8k5RUcm_CL2FaYdrDEdfbqRasgSgIatsh2YdSuNjU)

I tried a couple of res myself, its resizing for me. I m using Sequoia b.t.w

**Comment by phillipthelen** [comment]
As a test I set the minimum sizes to 1280 width and 400 height.

<img width="1392" alt="Screenshot 2024-11-08 at 11 33 21" src="https://github.com/user-attachments/assets/a9e32c63-3977-4833-a416-6349fe605946">


The width currently can't be smaller, because the table title bar breaks quickly. The height of 400 obviously is not the most useful size, but does work without breaking the UI, since the table can be scrolled. Which is what I would expect from a minimum size of a UI. I think this would make a reasonable minimum size that should definitely fix the issue described here.

**Comment by alinnert** [comment]
I totally agree with @phillipthelen. You can make most windows extremely small. This can still be useful though if you dock NeoHTop to the top or bottom of the screen and you only want to e.g. keep an eye on CPU usage and memory.

**Comment by Abdenasser** [comment]
should be available in next release (v1.0.9)
