### ISSUE TITLE
Problem with signature key when building for production

### ISSUE THREAD

**Issue by Cuchulain** [Abdenasser/neohtop#30]
Build for production on macOS does not work. It reports a problem with unknown author key when signing the application.
```
macOS Sequoia 15.1 (24B83)
xcode-select version 2409
```
![CleanShot 2024-11-07 at 09 08 25@2x](https://github.com/user-attachments/assets/594cc9df-a95d-42eb-acf4-624af606a494)

**Comment by Abdenasser** [comment]
you are trying to build with and sign with my personal Identity and certificate, without having the required environment variables and secrets for apple developer account

**Comment by Cuchulain** [comment]
Yes, I understood that. You have this command in README.md, so I tried it.
It doesn't give any information about the need to set a signature, so I thought I'd report it 🙂 
```
# Install dependencies
npm install

# Run in development mode
npm run tauri dev

# Build for production
npm run tauri build

# Build universal macOS binary
./build-universal.sh
```

**Comment by Abdenasser** [comment]
just use `npm run tauri build`
