### ISSUE TITLE
Process grouping

### ISSUE THREAD

**Issue by autaut03** [Abdenasser/neohtop#31]
Hey. Thanks for an awesome project :)

Nowadays processes usually have a couple (or a dozen) of child processes. For example, Arc browser, based on Chromium, has 30 "Helper" processes scattered around. This makes it harder to track what processes are running and how much total CPU/memory they're utilizing. 

With MacOS's Activity Monitor, there's an option to display processes hierarchically, but it's pretty ugly and doesn't actually display totals. So the request is to add a grouping option with proper totals and a good UX :)

**Comment by learning-thing** [comment]
Definetely need grouping! And maybe:
Summed up total Memory and/or CPU usage of a group | perhaps a toggle to switch between: Main/Parent and Highest.
And Total Process count of a group.

**Comment by brainiacakinz** [comment]
okay

**Comment by Abdenasser** [comment]
this has been added as a feature of the process details model, opening the modal now will give you a table of all subprocesses and their stats + totals, a release is on the way
