### ISSUE TITLE
support brew

### ISSUE THREAD

**Issue by Omid888** [Abdenasser/neohtop#34]
How to install the program using `brew` on macOS?

**Comment by edoardottt** [comment]
+1 installing it using brew would be great

**Comment by Abdenasser** [comment]
yeah it's too early

**Comment by junminhong** [comment]
@Abdenasser 
https://github.com/Homebrew/homebrew-cask/pull/191295
This PR has been merged, and neohtop is now available for installation via Homebrew. 🚀

**Comment by Abdenasser** [comment]
@junminhong this is amazing, thank you.

**Comment by Abdenasser** [comment]
here's the link [`brew install --cask neohtop`](https://formulae.brew.sh/cask/neohtop)
