### ISSUE TITLE
Windows task manager like process grouping

### ISSUE THREAD

**Issue by iceteacandy** [Abdenasser/neohtop#39]
Is it possible to have processes grouped together if they are related? For instance, in task manager in windows, all discord processes are under the drop down of discord. So if i want to kill the discord application completely, I can just kill the top processes, in contrast to searching through top (on linux) for all the related processes and killing them individually. Feel free to correct me if I've been doing it the wrong way. 
Thank you

**Comment by iceteacandy** [comment]
I meant to open it under Feature request, apologies for the wrong label

**Comment by Abdenasser** [comment]
please use the issue templates
