### ISSUE TITLE
[Windows 10] CPU Usage, Network I/O, and Storage Metrics Not Displaying 

### ISSUE THREAD

**Issue by ErfanTech** [Abdenasser/neohtop#40]
In the Windows Nightly Build v1.0.6 of the application, the monitoring dashboard does not display CPU usage, network I/O, or storage metrics. The sections where these metrics should appear are blank.

OS: Windows 10
Application Version: Nightly Build v1.0.6

![Captuggre](https://github.com/user-attachments/assets/a058d986-9c5e-411c-8802-62d2c58b6428)

**Comment by Abdenasser** [comment]
tried it on windows 11, it doesn't only get the network and storage stats ... will check on a windows 10 machine

**Comment by GeorgeV220** [comment]
Same thing in W11 24H2

**Comment by Abdenasser** [comment]
@laciferin2024 since you talked about this last time and since we are now supporting windows, would this be something interesting for you to spend some time on? otherwise I can work on a fix myself.

**Comment by NoPlagiarism** [comment]
For Disk Usage. Those lines must be reworked

https://github.com/Abdenasser/neohtop/blob/6892baa65eb579aa3027ab53a9de3d776a70cff2/src-tauri/src/main.rs#L126-L129

**Comment by NoPlagiarism** [comment]
https://github.com/Abdenasser/neohtop/blob/6892baa65eb579aa3027ab53a9de3d776a70cff2/src-tauri/src/main.rs#L145

`load_average()` don't work with Windows properly. See more in https://github.com/GuillaumeGomez/sysinfo/issues/624

**Comment by Abdenasser** [comment]
@NoPlagiarism would you be able to open a PR?

**Comment by NoPlagiarism** [comment]
I can only fix Disk Usage

I don't know what to do with Network I/O and especially what to do with load_average

**Comment by Abdenasser** [comment]
should be fixed next release

**Comment by NoPlagiarism** [comment]
Network I/O is still not displayed properly
