### ISSUE TITLE
Add support for a configuration file

### ISSUE THREAD

**Issue by chrede88** [Abdenasser/neohtop#41]
**Is your feature request related to a problem? Please describe.**
At the moment only a few settings are preserved between sessions, like the chosen theme. But not which columns to show or how many processes per page etc.

I can see the value in resetting these settings between sessions, but some people (myself included) would like to set a nice default that might not be the current default.

**Describe the solution you'd like**
I think the best option is to allow for a config file, where the exact state can be set. This would also allow to sync setups between machines.

**Describe alternatives you've considered**
Another option is to keep state between sessions, but that doesn't allow syncing the setups between machines.

**Additional context**
The most obvious place to add a config file is `~/.config/neohtop/`, at least on unix based systems (won't even pretend to know where this stuff is normally kept on Windows).

**Comment by Abdenasser** [comment]
can you use the feature request template, or otherwise start a discussion in discussions tab.

**Comment by chrede88** [comment]
> can you use the feature request template, or otherwise start a discussion in discussions tab.

Now using the request template.
Just an FYI, you've to enable discussions for this repo. Currently, the link hits a 404.

**Comment by Abdenasser** [comment]
sure

**Comment by gnesh** [comment]
how get

**Comment by Pinguin2001** [comment]
On Windows, app data is stored in:

System wide installed apps: C:\ProgramData\<AppName>

User installed apps: C:\Users\<UserName>\AppData\Local\<AppName>
