### ISSUE TITLE
Latest Release

### ISSUE THREAD

**Issue by daeho-ro** [Abdenasser/neohtop#46]
**Describe the bug**
Hello, it seems that the github latest release is marked on the nightly build, can you change it to the v1.0.5?

**Comment by Abdenasser** [comment]
@daeho-ro a new build is getting generated

**Comment by Abdenasser** [comment]
@daeho-ro we might also need to slightly modify the URLs in that PR to the new format (releases are generating using a workflow now)
here is the latest release [https://github.com/Abdenasser/neohtop/releases/tag/v1.0.8](https://github.com/Abdenasser/neohtop/releases/tag/v1.0.8)

**Comment by daeho-ro** [comment]
Thank you @Abdenasser !
