### ISSUE TITLE
This doesn't support linux ?

### ISSUE THREAD

**Issue by iysheng** [Abdenasser/neohtop#47]
**Is your feature request related to a problem? Please describe.**

I tested  this tool on windows 10, looks pretty, and I try to build on a  linux laptop, But it failed.
The tool doesn't support linux right ?

**Comment by Abdenasser** [comment]
@iysheng 🤔 don't you watch the news buddy?

**Comment by Abdenasser** [comment]
check this out [https://abdenasser.github.io/neohtop/](https://abdenasser.github.io/neohtop/)

**Comment by iysheng** [comment]
> @iysheng 🤔 don't you watch the news buddy?

aha, thks, I just read the readme before. and when build failed as
![image](https://github.com/user-attachments/assets/e5f52a8e-2381-4257-9d43-8664cfa27149)

**Comment by Abdenasser** [comment]
@iysheng no worries, let me know if it doesn't work properly for you.

**Comment by iysheng** [comment]
aha, I couldn't use this tool, for the linux latop installed server edition without GUI support.
``(NeoHtop:2688032): Gtk-WARNING **: 09:07:57.263: cannot open display:``

**Comment by Abdenasser** [comment]
what architecture ?

**Comment by iysheng** [comment]
> what architecture ?

X86-64, I connect the laptop use ssh

**Comment by rcv11x** [comment]
I have just downloaded only the `.AppImage`, I have given it permissions to run and it does not work, the neohtop window opens in white and in the console I get the message: 

```
Could not create default EGL display: EGL_BAD_PARAMETER. Aborting...

** (NeoHtop:10945): WARNING **: 09:34:17.298: atk-bridge: get_device_events_reply: unknown signature
```
![Captura de pantalla_20241108_093412](https://github.com/user-attachments/assets/b5e637f9-ef07-40c0-a902-f141e859e416)

I'm on Fedora 41 (KDE plasma 6.2.3) am I missing something? any dependencies? 

pd: i didn't build anything, i just downloaded the `.AppImage`

**Comment by Abdenasser** [comment]
how about the .deb @rcv11x did you try that?

**Comment by rcv11x** [comment]
> how about the .deb @rcv11x did you try that?

.deb? how do i install it in fedora if .deb is for debian/ubuntu?

**Comment by Abdenasser** [comment]
> > how about the .deb @rcv11x did you try that?
> 
> .deb? how do i install it in fedora if .deb is for debian/ubuntu?

those are built on ubuntu, but you can try using a tool like Alien, which converts .deb files to .rpm format

**Comment by iysheng** [comment]
> > how about the .deb @rcv11x did you try that?
> 
> .deb? how do i install it in fedora if .deb is for debian/ubuntu? 

you can use dpkg command crack the deb file
