### ISSUE TITLE
GPU stats

### ISSUE THREAD

**Issue by shizzgar** [Abdenasser/neohtop#5]
Yo man! Awesome work!
What about gpu usage stats? 
It will be awesome if I can view gpu usage stats through your app!

**Comment by Abdenasser** [comment]
@shizzgar that sounds really interesting, thank you!

**Comment by Abdenasser** [comment]
closing this for now as it's a feature request not an issue

**Comment by RoyiAvital** [comment]
Where should feature requests go?
As GPU stats are important to many these days.

**Comment by Abdenasser** [comment]
@RoyiAvital you can open an issue and add the feature request label

**Comment by RoyiAvital** [comment]
Wouldn't it be easier just to open this and add the tag?
