### ISSUE TITLE
Free and Cached memory showing NaN

### ISSUE THREAD

**Issue by outranker** [Abdenasser/neohtop#53]
**Describe the bug**
Free and Cached memory stats is showing NaN

**Screenshots**
<img width="1277" alt="Screenshot 2024-11-08 at 5 28 46 PM" src="https://github.com/user-attachments/assets/f2b19b92-7805-42d0-9e91-7ba24af0b963">

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.0.1
 - Version 0.1.0 (20241101.031629)

**Comment by Abdenasser** [comment]
@outranker update to last version
