### ISSUE TITLE
High CPU Usage on M3Pro Macbook Pro

### ISSUE THREAD

**Issue by arjun-com** [Abdenasser/neohtop#55]
**Describe the bug**
CPU Usage fluctuates between 8% and 12% which seems pretty high for a system monitoring app.

**To Reproduce**
1. Open Neohtop.
2. Look at the app.

**Expected behavior**
CPU Usage hovering at around 1% to 2% would be a good estimate for a system monitoring app.

**Screenshots**
![image](https://github.com/user-attachments/assets/de86c33a-bf93-4285-8bc7-1f5b3c55d8b0)

**Desktop (please complete the following information):**
 - MacOS 15.1
 - Macbook Pro M3 Pro ( 18GB ram )
 - Neohtop 1.0.5

**Comment by Abdenasser** [comment]
what percentage do you aim for?

**Comment by jatindotdev** [comment]
think its normal in my case it stays  consistent ~6.5, can go 7-9 sometimes, as activity manager uses almost same amount ~10 ish sometimes

**Comment by Abdenasser** [comment]
> think its normal in my case it stays consistent ~6.5, can go 7-9 sometimes, as activity manager uses almost same amount ~10 ish sometimes
> 
> @Abdenasser i love the idea and the app

thank you sir, @arjun-com if you change the refresh rate to something greater than 1s it will give you a better result (I've personally done all possible optimisations already, but would appreciate if someone can take time to make it even better)

**Comment by mister-good-deal** [comment]
On **Ubuntu 24.04** using master dev local build from **8269d6f95a41df5fd31b175f26113b1692b6163c**

Here is the CPU usage i've got from different refresh rate.

**Refresh rate 5 sec ~= 5%**

![Image](https://github.com/user-attachments/assets/bf8cb6ac-303c-42af-84ad-093a1d22b9da)


**Refresh rate 2 sec ~= 15%**

![Image](https://github.com/user-attachments/assets/634a6649-6df5-4e25-a4b1-782cae0fd4af)


**Refresh rate 1sec ~= 30%**

![Image](https://github.com/user-attachments/assets/7d802a04-b3bf-40b8-9118-9bd1f62a341a)

For a refresh rate of 5 sec CPU usage seems OK (lower than 10%) but for shorter refresh rate I think the CPU usage is a bit high for a performance monitoring tool.

I don't know where those CPU come from (front or back), I can investigate a bit if you tell me how to quickly.
