### ISSUE TITLE
Absurdly high memory usage of `WebKitWebProces` after a while

### ISSUE THREAD

**Issue by Sharktheone** [Abdenasser/neohtop#68]
**Describe the bug**

WebKit which gets invoked by tauri uses way too much memory for such an application, I've seen it go up to 5300MB. 
If I need to guess, this is probably a problem in a JS script, that stores too much history information in an array or something. 

**To Reproduce**
1. Open NeoHtop
2. Wait some time (In my case ~24h)
3. See high memory usage

**Expected behavior**
Don't use as much memory

**Screenshots**
![image](https://github.com/user-attachments/assets/ac5fada6-d0b3-4afe-a54b-35c22802ada6)

![image](https://github.com/user-attachments/assets/ad9dee52-21c8-4ba4-825e-efddacb16a48)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Kernel 6.11.5-zen1-1-zen
 - 1.0.5 (I need to check with the latest)

**Additional context**
I've checked for other bug reports of this problem, but didn't find any other issues. If I missed one, please point me out to them.

**Comment by Abdenasser** [comment]
you're stats look really weird, 0.6% CPU, 5.2Gib of ram ... just use `htop` or `btop` bro. 
`brew install htop`
