### ISSUE TITLE
Network I/O not working!

### ISSUE THREAD

**Issue by Dominiquini** [Abdenasser/neohtop#70]
**Describe the bug**
The panel for 'Network I/O' is not working! Always show '0.0 B/s' for 'Receiving' or 'Sending'!

**To Reproduce**
1. Open NetHtop (with or without sudo)
2. View the 'Network I/O' panel
3. See the info showing 0.0 B/s

**Expected behavior**
The panel should display the network activity

**Screenshots**
![NeoHtop](https://github.com/user-attachments/assets/da69965a-f2f7-4fc5-b783-3e035adaca5e)

**Desktop (please complete the following information):**
 - OS: Linux EndeavourOS 6.10.10 (KDE Plasma 6.2.3 - X11)
 - Version: 1.0.8

**Additional context**
Installed from the aur: https://aur.archlinux.org/packages/neohtop-bin

Thanks

**Comment by Abdenasser** [comment]
installing from unofficial sources is at your own risk.

**Comment by Dominiquini** [comment]
> installing from unofficial sources is at your own risk.

I tried download an run the AppImage, and the same thing happens!

**Comment by Abdenasser** [comment]
I just tried and it's working fine

**Comment by Dominiquini** [comment]
I tried to compile myself and the same problem! All appears to be working fine, only the Network I/O panel that shows only 0.0 B/s!
It's possible that the application is monitoring the wrong interface?

Sorry to bother you with this problem I'm having!
Thanks

**Comment by Abdenasser** [comment]
@Dominiquini can you try playing a Youtube video for example and see if those change, mine is most of the time 0 until i start downloading something, otherwise it could be an interface problem (will appreciate it if you can share your system info for me to debug this a bit more later)

**Comment by Dominiquini** [comment]
> @Dominiquini can you try playing a Youtube video for example and see if those change, mine is most of the time 0 until i start downloading something, otherwise it could be an interface problem (will appreciate it if you can share your system info for me to debug this a bit more later)

Below is a print showing the difference in measuring network activity! In addition to YouTube, I also ran a speed test in the background and didn't see any network activity on this app!

![NeoHtop](https://github.com/user-attachments/assets/80fd9013-2c3c-4b87-bad5-f2ed4f4f2042)

I tried to run the AppImage version and the locally compiled! I tried also with or without sudo! All show the same behavior!

Tell me what more I can share to help! The application don't produce any log on the terminal!

Thanks

**Comment by Abdenasser** [comment]
thank you, that's enough for the moment.. i'll find time to work on a fix for that

**Comment by oppZ** [comment]
i have the same issue on my ubuntu 24.04.1

**Comment by Dominiquini** [comment]
Some more info on my system:

```
                     ./o.                   liveuser@EndeavourOS
                   ./sssso-                 --------------------
                 `:osssssss+-               OS: EndeavourOS x86_64
               `:+sssssssssso/.             Kernel: Linux 6.10.10-arch1-1
             `-/ossssssssssssso/.           Uptime: 5 hours, 54 mins
           `-/+sssssssssssssssso+:`         Packages: 3334 (pacman)
         `-:/+sssssssssssssssssso+/.        Shell: bash 5.2.37
       `.://osssssssssssssssssssso++-       Display (23MB35): 1920x1080 @ 60 Hz in 23" [External]
      .://+ssssssssssssssssssssssso++:      DE: KDE Plasma 6.2.3
    .:///ossssssssssssssssssssssssso++:     WM: KWin (X11)
  `:////ssssssssssssssssssssssssssso+++.    WM Theme: Breeze
`-////+ssssssssssssssssssssssssssso++++-    Theme: Breeze (Dark) [Qt], Breeze-Dark [GTK2], Breeze [GTK3/4]
 `..-+oosssssssssssssssssssssssso+++++/`    Icons: breeze-dark [Qt], breeze-dark [GTK2/3/4]
   ./++++++++++++++++++++++++++++++/:.      Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
  `:::::::::::::::::::::::::------``        Cursor: Breeze_Light (24px)
                                            Terminal: konsole 24.8.3
                                            Terminal Font: MesloLGSDZ Nerd Font (10pt)
                                            CPU: Intel(R) Core(TM) i7-6700K (8) @ 4.20 GHz
                                            GPU 1: NVIDIA GeForce GTX 1060 6GB
                                            GPU 2: Intel HD Graphics 530 @ 1.15 GHz [Integrated]
                                            Memory: 26.17 GiB / 31.21 GiB (84%)
                                            Swap: Disabled
                                            Disk (/): 17.84 GiB / 20.00 GiB (89%) - overlay
                                            Disk (/run/archiso/bootmnt): 2.77 GiB / 2.77 GiB (100%) - iso9660 [Read-only]
                                            Disk (/run/media/liveuser/Files): 3.22 TiB / 3.64 TiB (88%) - ntfs3
                                            Disk (/run/media/liveuser/Programs_01): 1.64 TiB / 1.82 TiB (90%) - ntfs3
                                            Disk (/run/media/liveuser/Programs_02): 836.98 GiB / 931.39 GiB (90%) - ntfs3
                                            Disk (/run/media/liveuser/Windows_10): 429.00 GiB / 465.16 GiB (92%) - ntfs3
                                            Local IP (wlan0): 192.168.0.100/24
                                            Locale: en_US.UTF-8
```
Maybe I should have mentioned that I'm using a live media!

Thanks again!

**Comment by MrMDrX** [comment]
I can confirm I have the same problem on Manjaro KDE plasma 6 wayland session.

**Comment by Abdenasser** [comment]
@Dominiquini @MrMDrX @oppZ https://github.com/Abdenasser/neohtop/releases/tag/v1.1.0

**Comment by Dominiquini** [comment]
> @Dominiquini @MrMDrX @oppZ https://github.com/Abdenasser/neohtop/releases/tag/v1.1.0

It's working now!

Thanks!
