### ISSUE TITLE
Missing app icons

### ISSUE THREAD

**Issue by egoist** [Abdenasser/neohtop#73]
**Describe the bug**
Many apps only show up with the default ghost icon

**To Reproduce**
just look at the neohtop process

**Expected behavior**
show their app icon

**Screenshots**

![CleanShot 2024-11-09 at 15 42 23@2x](https://github.com/user-attachments/assets/1f7998d3-b23b-4d01-8b4c-ca2cdb1980a6)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 22] 15.2

**Additional context**

**Comment by Abdenasser** [comment]
that's not a bug, unless you wanna take some time to add NeoHtop to simpleIcons
