### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by Jirubizu** [Abdenasser/neohtop#8]
Any future plans to have complete linux support?

**Comment by Abdenasser** [comment]
yes we have plans for that @laciferin2024

**Comment by laciferin2024** [comment]
What is the blockers at the moment? Perhaps u can delegate tasks one by one

**Comment by Abdenasser** [comment]
only blocker for me is the lack of a linux machine where I can test this out (will maybe use a VM)

**Comment by Pinguin2001** [comment]
> only blocker for me is the lack of a linux machine where I can test this out (will maybe use a VM)

I could try it on my laptop running arch linux, it is already setup for tauri development anyway. Maybe I find some time this evening, if not tomorrow.

I will report back what works and what doesn't.

**Comment by Abdenasser** [comment]
will wait for your PR then @Pinguin2001

**Comment by Jelloeater** [comment]
@Abdenasser 
VMware Workstation is free, also VirtualBox.
I'd use the heck out of this if you make a version for Ubuntu.

**Comment by Abdenasser** [comment]
yeah, last time I checked those they were not supporting apple silicon .. but will check again

**Comment by DropB1t** [comment]
I can try to build Neohtop on my Ubuntu laptop and bundle it into a Debian package by using Tauri.

**Comment by razor950** [comment]
I built this via WSL 2 and it works fine. I had to install rust and cargo along with node 18 as this project uses newer node features.
Aside from that I got no issues, I might setup a quick github actions in a fork and submit as a PR if wanted.

![image](https://github.com/user-attachments/assets/178b1fc0-0eb6-4d9e-9206-66099b2397a3)

**Comment by Abdenasser** [comment]
amazing, thank you @razor950 can you also check the latest bug fixes I just pushed .. is that a Xeon CPU btw ?

**Comment by Abdenasser** [comment]
@DropB1t @razor950 I think I can bundle for linux from mac as well, but contributions are welcome of course.

**Comment by LaDaniWapa** [comment]
Have anyone encounter any libs depencency errors? I'm trying to build t on Linux Mint 22 Wilma. The proyect needs libwebkit2gtk2-4.0, but the only dev package that I have available is the v4.1, which is installed and still gives me the error.

btw this is the error just in case I didn't properly understand it:
```
 > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags webkit2gtk-4.0 webkit2gtk-4.0 >= 2.22

  The system library `webkit2gtk-4.0` required by crate `webkit2gtk-sys` was not found.
  The file `webkit2gtk-4.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
  The PKG_CONFIG_PATH environment variable is not set.
```

**Comment by razor950** [comment]
@Abdenasser no, AMD Ryzen 9 5950x and it builds fine off latest git release

**Comment by Abdenasser** [comment]
great and thank you @razor950 glad you like it

**Comment by Abdenasser** [comment]
> Have anyone encounter any libs depencency errors? I'm trying to build t on Linux Mint 22 Wilma. The proyect needs libwebkit2gtk2-4.0, but the only dev package that I have available is the v4.1, which is installed and still gives me the error.
> 
> btw this is the error just in case I didn't properly understand it:
> 
> ```
>  > PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags webkit2gtk-4.0 webkit2gtk-4.0 >= 2.22
> 
>   The system library `webkit2gtk-4.0` required by crate `webkit2gtk-sys` was not found.
>   The file `webkit2gtk-4.0.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.
>   The PKG_CONFIG_PATH environment variable is not set.
> ```

be careful, of not breaking your system dependencies

**Comment by LaDaniWapa** [comment]
I got it to work after migrating it to tauri 2.0! :D

![image](https://github.com/user-attachments/assets/911b983e-1041-40d5-a90b-af0626d32efb)

**Comment by Abdenasser** [comment]
@LaDaniWapa thank you, can you push a PR with the migration!

**Comment by mnott** [comment]
I can't install under Linux

```bash
436 timing build:link Completed in 6ms
437 info run @sveltejs/kit@2.7.3 postinstall node_modules/@sveltejs/kit node postinstall.js
438 info run esbuild@0.21.5 postinstall node_modules/esbuild node install.js
439 info run @sveltejs/kit@2.7.3 postinstall { code: 1, signal: null }
440 info run esbuild@0.21.5 postinstall { code: 0, signal: null }
441 timing build:run:postinstall:node_modules/esbuild Completed in 123ms
442 timing reify:rollback:createSparse Completed in 415ms
443 timing reify:rollback:retireShallow Completed in 0ms
444 timing command:install Completed in 5565ms
445 verbose stack Error: command failed
445 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
445 verbose stack     at ChildProcess.emit (events.js:314:20)
445 verbose stack     at maybeClose (internal/child_process.js:1022:16)
445 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
446 verbose pkgid @sveltejs/kit@2.7.3
447 verbose cwd /home/tc/sub/neohtop
448 verbose Linux 5.15.0-70-generic
449 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
450 verbose node v12.22.9
451 verbose npm  v8.5.1
452 error code 1
453 error path /home/tc/sub/neohtop/node_modules/@sveltejs/kit
454 error command failed
455 error command sh -c node postinstall.js
456 error file:///home/tc/sub/neohtop/node_modules/@sveltejs/kit/postinstall.js:7
456 error 	const cwd = process.env.INIT_CWD ?? process.cwd();
456 error 	                                  ^
456 error
456 error SyntaxError: Unexpected token '?'
456 error     at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
456 error     at async link (internal/modules/esm/module_job.js:42:21)
457 verbose exit 1
458 timing npm Completed in 5779ms
459 verbose unfinished npm timer reify 1730894307412
460 verbose unfinished npm timer reify:build 1730894312445
461 verbose unfinished npm timer build 1730894312446
462 verbose unfinished npm timer build:deps 1730894312446
463 verbose unfinished npm timer build:run:postinstall 1730894312458
464 verbose unfinished npm timer build:run:postinstall:node_modules/@sveltejs/kit 1730894312458
465 verbose code 1
466 error A complete log of this run can be found in:
466 error     /root/.npm/_logs/2024-11-06T11_58_27_201Z-debug-0.log
```

**Comment by Pinguin2001** [comment]
I have successfully built https://github.com/Abdenasser/neohtop/commit/63405d8d5491c4c67df482ca4b7e59b638174cea with no changes needed whatsoever

![image](https://github.com/user-attachments/assets/f3372017-8f8a-4f81-876a-37320639c32c)

**Comment by lkxe** [comment]
I used Tauri's migrate script to migrate to V2. It now compiles on Arch and Hyprland without any problems.
![image](https://github.com/user-attachments/assets/90f3bede-2367-4cd9-829c-1e0ef96addb5)

**Comment by laciferin2024** [comment]
Its all thanks to `sysinfo`. It even supports Windows

**Comment by DropB1t** [comment]
Compiled on Ubuntu **24.10** with migration to Tauri **2.0**, seems to work perfectly. Want also to see if it is possible to compile without migrating to the new version of Tauri. I also managed to generate a `.deb` package and install it via `dpkg` tool.

![Screenshot From 2024-11-06 19-27-16](https://github.com/user-attachments/assets/5b623a03-6e54-4aad-9c0e-55c35c18763a)

Worth mentioning that in order to build NeoHtop on a Debian system (i.e. Ubuntu) you need to install these dependencies:
```
sudo apt install libglib2.0-dev libgtk-3-dev libjavascriptcoregtk-4.1-dev libsoup-3.0-dev libwebkit2gtk-4.1-dev
```

To build run this `tauri` command:
```
npm run tauri build -- --target x86_64-unknown-linux-gnu --bundles deb
```

**Comment by Abdenasser** [comment]
let me see if I can build it, I'll post the **.deb** file her if someone wanna try it, then we can include it in the release for all people to download (will need to setup CI and github actions at some point)

**Comment by drivemeca** [comment]
Compiled and installed via deb on Ubuntu Budgie 24.04.1. Thanks
![Snapshot_2024-11-06_14-57-53](https://github.com/user-attachments/assets/537947ed-3631-42f1-bcdc-fd9ccef464d2)

**Comment by Abdenasser** [comment]
@DropB1t @laciferin2024 @Pinguin2001 can you guys test this Linux .deb I just added to v1.0.5 https://github.com/Abdenasser/neohtop/releases/tag/v1.0.5

**Comment by DropB1t** [comment]
@Abdenasser Unfortunately my system is x86_64 and not arm64, in the mentioned release you provided only the latter target package.

**Comment by Abdenasser** [comment]
@DropB1t we should also support that, would release a build for it in a few

**Comment by DropB1t** [comment]
@Abdenasser no problem 👍🏻, just ping me as soon as you need to test it

**Comment by abdo0nasser** [comment]
@Abdenasser I can test  it for my x64 machine running arch linux whenever you ping me
