### ISSUE TITLE
Update Button Not Working

### ISSUE THREAD

**Issue by back2Lobby** [Abdenasser/neohtop#85]
**Describe the bug**
The update button is not working at all.

**To Reproduce**
1. Click the info icon
2. Click the update button

**Expected behavior**
Start updating or something like that.

**Screenshots**
![Screenshot from 2024-11-10 10-51-36](https://github.com/user-attachments/assets/3c899905-efb9-44a1-8b1b-90a927c1ca6a)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 24

**Additional context**
I installed the app using deb package.

**Comment by back2Lobby** [comment]
I just figured its a link pointing to the repo. But I guess we need tauri `shell` plugin for links to work.

**Comment by Abdenasser** [comment]
> I just figured its a link pointing to the repo. But I guess we need tauri `shell` plugin for links to work.

https://github.com/Abdenasser/neohtop/releases/tag/v1.1.0
