### ISSUE TITLE
Display total system usage for all matching search items

### ISSUE THREAD

**Issue by aryanprince** [Abdenasser/neohtop#9]
# Summary

When I search for a term like ‘Arc,’ the results show multiple items (e.g., Arc Renderer, Arc Helper, etc.). It would be helpful if the app could sum up and display the total system usage for all items matching the search query, giving a quick overview of their combined impact.

## Screenshot

Idea is to display the system utilization total sum of all items that are shown, when I search for "Arc" (but of course, for any term you search).

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/163cf468-5520-4604-b598-0835c488a509">

**Comment by Abdenasser** [comment]
@aryanprince there a Arc itself is the parent process for all of those which means that the stats for Arc is already the sum of those
![Screenshot 2024-11-06 at 00 58 55](https://github.com/user-attachments/assets/6c537029-e375-4bc7-bc53-78c7dae653e7)

searching by parent id
![Screenshot 2024-11-06 at 00 59 06](https://github.com/user-attachments/assets/47ecca85-e7f5-4038-a070-7967d7493dfe)

**Comment by Abdenasser** [comment]
is this something that other tools are doing? can you give an example?

**Comment by Pinguin2001** [comment]
Windows Task Manager is the only app I can think of that does this.

It helps reduce the clutter, however it should absolutely be toggleable

**Comment by Abdenasser** [comment]
will think about it, thanks!

**Comment by aryanprince** [comment]
> is this something that other tools are doing? can you give an example?

@Abdenasser I’ve tried several popular `top` alternatives, like [htop](https://github.com/htop-dev/htop) and [btop](https://github.com/aristocratos/btop), but none make it easy to view combined resource usage for an app with multiple sub-processes.

On macOS especially, many apps (like VS Code, Adobe Creative Cloud, Raycast, and TeamViewer) spawn multiple sub-processes. I can think of 2 solutions:

1. When you search “Code,” it could sum up memory/CPU usage for all items that match “Code” in the search. This would so clutch and I couldn't find a tool to do this _easily_.
2. Or, like @Pinguin2001 mentioned, add a toggle to let users see resources per app, that includes all its related sub-processes grouped together.

## Screenshots

Here are some screenshots from Activity Monitor, but it's same processes shown on any of these `top` apps, including `neohtop`.

<details><summary>Arc Usage</summary>
<p>

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/4f33c708-b1ca-4f88-bda1-6faadfeef5fe">

</p>
</details> 

<details><summary>VS Code Usage</summary>
<p>

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/c205d341-b23a-44ce-89e6-cdf40c92010c">

</p>
</details> 

<details><summary>Adobe Creative Cloud Usage</summary>
<p>

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/c29ab000-3ac6-426a-a84d-6ea4b192d627">

</p>
</details> 

<details><summary>TeamViewer Usage</summary>
<p>

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/2f632961-2b4b-418b-9251-3ff7d43c5b21">

</p>
</details>
