### ISSUE TITLE
Add kind (intel/mac) column on apple silicon, and remove min loading time?

### ISSUE THREAD

**Issue by jose-manuel-silva** [Abdenasser/neohtop#97]
So its two things, first is self explanatory, the second, when i opened the app i noticed it took a while to open, went to check why, and saw that there is a min loading time for the loading screen on the main +page.svelte, is there a reason for that? Or can that be removed? (And maybe remove the entire loading screen all together, or only show it after 0.5s for example)

**Comment by Abdenasser** [comment]
@jose-manuel-silva min loading time is meant to be there, what do you mean by Add kind (intel/mac) column on apple silicon, and where?

**Comment by jose-manuel-silva** [comment]
Just curious, is there a reason for the loading time? Or its just a design decision?

The kind column is to show if a process is x86 (intel) or arm (mac)
<img width="855" alt="Screenshot 2024-11-11 at 01 18 51" src="https://github.com/user-attachments/assets/9325d151-9c80-4cf5-bcd9-8ef3d616c94f">
